### ISSUE TITLE
Layout Issue(?)

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#23]
Jenn Brown sent this as an email yesterday. I wonder what's going on. 

"Sending this as an email instead of adding to the tracking doc because I want to send a few screen grabs.
Seeing this formatting issue in model windows in which the image is taller than wide.
The caption starts to the right of the image then wraps under the image. I could replicate the problem in both  Firefox (first image) and Safari (second image).
I don't  necessarily want the image to be made larger (to fill the width of the modal) because for portrait images, that would make them very large but just want the caption to start under the image no matter how wide it is.
Does that make sense?"
![Screen Shot 2022-01-11 at 4 26 10 PM](https://user-images.githubusercontent.com/59982410/149222121-1327b1cb-9a84-4e41-b3b1-f81c80c7b210.png)
![Screen Shot 2022-01-11 at 4 25 27 PM](https://user-images.githubusercontent.com/59982410/149222133-6550ff83-4a5c-46a8-989b-2122bdd03e30.png)

**Comment by superjai** [comment]
Hey @mspector13 - I have figured out the issue with modal windows where the text wraps to the right of the image (like the one featured in this issue). The problem has nothing to do with whether the image is a jpg or png - or whether the modal window contains multiple tabs (some avenues that I pursued). 

Instead the issue is much simpler: when the text is wrapping it is because the images are simply not wide enough. I did some testing and it looks like images that are **at least 800 pixels wide** won't have the text wrapping problem. So, for all modal windows where I flagged the text wrapping, the offending images just need to be rescaled to a larger width. If people don't want a particular image to be any bigger, they can just add white space to pad the width.

**Comment by mspector13** [comment]
Righteous! Thanks so much @superjai! I saw that you also cc'd Jenn in an email. Hopefully the image owners can simply provide a larger image, I'm concerned that adding white space to particular modals could serve as an artifact down the line if the image gets replaced. As long as we document it though, it should be alright.

**Comment by mspector13** [comment]
Two options (in Gimp): 

Image --> Canvas size
Image --> Scale image
