### ISSUE TITLE
create modal even if no image, but have caption

### ISSUE THREAD

**Issue by bbest** [noaa-onms/ocnms#25]
Update: there are other modals that might have a caption, but no text (e.g., `kelp-forest_benthic-intertebrates.Rmd`). `insert_figure()` needs arguments for both figures *and* captions. What do?

_Originally posted by @mspector13 in https://github.com/noaa-onms/ocnms/issues/18#issuecomment-1013441270_

**Comment by mspector13** [comment]
Fixed by @bbest 

[+ insert_caption() #26; delete unused modals; · noaa-onms/ocnms@9902d03](https://github.com/noaa-onms/ocnms/commit/9902d034bf85f0f9b2a073824ff78d98f0d20bab)
[add caption from GSheet into Rmds with dynamic figures · Issue #26 · noaa-onms/ocnms](https://github.com/noaa-onms/ocnms/issues/26#issuecomment-1015698839)
