### ISSUE TITLE
Modal funk: new modals w/o .Rmd files

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#30]
Hey @bbest and @superjai, 

I've been trying to sort out the issues identified in Jai's  [OCNMS Modal Window Problems](https://docs.google.com/spreadsheets/d/1CI7lxXOcA7uvKCpzNez-nu97EF1AIXtnVfKkdzCp0G8/edit#gid=0) and I realized that there are many modals that don't yet exisit. For example, there is currently no `Military activity` modal in Human Connections in the [master spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539) (nor in the repo). 

How do we resolve this? `Military Activity` *should* be a modal window, there *should* be `human-connections_military-activity.Rmd` but it doesn't yet exist. Apologies if I'm missing something obvious here

**Comment by bbest** [comment]
Hi @mspector13,

I see a modal for [Human Connections](https://noaa-onms.github.io/ocnms/human-connections.html) -> [Military activity](https://noaa-onms.github.io/ocnms/modals/human-connections_military-activity.html):

![image](https://user-images.githubusercontent.com/2837257/150056326-e22cab5a-7f85-45af-a208-f610442d6dd3.png)

based on these files:

1. [modals/human-connections_military-activity.Rmd](https://github.com/noaa-onms/ocnms/blob/9abde878d3bb0c91ae8d2bb8d2dc2eef0c946163/modals/human-connections_military-activity.Rmd)
1. [modals/human-connections_military-activity.html](https://github.com/noaa-onms/ocnms/blob/9abde878d3bb0c91ae8d2bb8d2dc2eef0c946163/modals/human-connections_military-activity.html)

because:

1. An entry was made in the `modals` sheet of [Master_OCNMS_infographic_content - Google Sheets](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1778111652):
  ![image](https://user-images.githubusercontent.com/2837257/150056122-325348c9-8774-4895-9936-5982f10c508f.png)

1. [`render_site.R`](https://github.com/noaa-onms/ocnms/blob/master/render_site.R) was ran to create the modals.

I however do not see any entries for this modal in the `figures` sheet of [Master_OCNMS_infographic_content - Google Sheets](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1778111652), which is why there are no figures in the modal. 

Is that what you're asking about?  Or perhaps you were looking at an old version of the Github site.

**Comment by mspector13** [comment]
Hey @bbest, 

Thanks for clarifying. Since there isn't an entry for this modal in the `figures` tab of the [Master_OCNMS_infographic_content - Google Sheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1778111652) (and others in the same case), should I go ahead and make an entry manually?

I'm still a little fuzzy on the actually workflow here, in this case I think it's better to ask permission rather than forgiveness!
