### ISSUE TITLE
Something in render_site.R overrides `insert_caption()`?

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#33]
Last night I went through @superjai   [OCNMS Modal Window Problems](https://docs.google.com/spreadsheets/d/1CI7lxXOcA7uvKCpzNez-nu97EF1AIXtnVfKkdzCp0G8/edit#gid=0) spreadsheet and added @bbest's

`insert_caption()` 

function to the modals that needed captions added. Everything was working smoothly. However, it looks like re-rendering the site and pushing changes a la `render_site.R` this code was overwritten. 

Any ideas?

<img width="1197" alt="Screen Shot 2022-01-19 at 8 39 03 AM" src="https://user-images.githubusercontent.com/59982410/150174819-ae997c1c-f510-4e9c-b283-97042c60cb79.png">

**Comment by mspector13** [comment]
Ah, looks like @bbest checked in commits that overrode/ignored my commits. I'll go ahead and re-add in the function 
![Screen Shot 2022-01-19 at 10 55 09 AM](https://user-images.githubusercontent.com/59982410/150197566-027239a0-401b-4667-8741-ebaede2a2f89.png)

**Comment by mspector13** [comment]
Reopening this issue. 

*Something* is still overriding my additions to the .Rmd files. I re-added `insert_caption()` yesterday to *all* of the modal windows that needed it, today these same modals are back to being blank. 

What gives?

**Comment by superjai** [comment]
Hey @mspector13 
I did some digging and I now have an answer for you. Here is the code for [render_site.R](https://github.com/noaa-onms/ocnms/blob/master/render_site.R):

```
# update site ----
gsheets_to_csvs(gsheet) # downloads the Google Sheet tabs into separate data/*.csv files for quick reading
add_gimage_paths()      # adds image_path to data/gsheets/figures.csv

create_svg_links()      # create table (csv) that links svg icons to modal html links

create_modals()         # except where dynamic_modal == TRUE
render_modals()         # render static and dynamic modals

create_scenes()         # create scenes.Rmd (overview & habitats) with SVGs
render_site()   
```
The problem here lies with `create_modals()`, which rebuilds all modal windows from scratch. Meaning that - if you save anything extra into a modal Rmd - that extra stuff is going to get wiped out the next time that `create_modals()` is run. The one exception is if "dynamic_modal" is set to T in the modals tab of the Master OCNMS google spreadsheet (in which case, that particular Rmd will be left alone).

**Comment by mspector13** [comment]
Awesome, good looking out @superjai! I remember discussing this as a possible explanation the other day. Thanks for getting to the bottom of this. I'll go through and add `insert_caption()` yet again, and will be sure to set `except where dynamic_modal == TRUE` for the modals in question. 

Cheers,
