### ISSUE TITLE
Broken: Modals without content & Modals won't update w/ content

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#39]
Hey @bbest and @superjai, 

I've been trying to work through the modal that need TLC from [Issue 31](https://github.com/noaa-onms/ocnms/issues/31) when I came across some weirdness. 

Firstly, the `Human Connections- Science` appears to be fully populated:
![Screen Shot 2022-02-14 at 2 15 36 PM](https://user-images.githubusercontent.com/59982410/153955567-59aa88b7-c9d8-451c-8def-ff3f85660599.png)

Yet the .Rmd is blank: 
![Screen Shot 2022-02-14 at 2 15 55 PM](https://user-images.githubusercontent.com/59982410/153955596-da720667-3642-4e71-8e46-36c6f04823ff.png)

I realized this when I tried to populate `Human Connections - Education and Engagement` (which was also blank). All of the necessary info is in the [master spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539). However, the images _were not_ downloaded to `./ocnms/modals/figures`. I downloaded them, and added the necessary content to the .Rmd script, but am still running into an error: 
![Screen Shot 2022-02-14 at 2 23 42 PM](https://user-images.githubusercontent.com/59982410/153956621-862851ae-36f9-488a-a7da-c4a3b1ccb457.png)
![Screen Shot 2022-02-14 at 2 24 01 PM](https://user-images.githubusercontent.com/59982410/153956644-f2e1898e-afab-49dd-84cd-9bfe02a30967.png)

I've run `render_site.R` a few times, everything looks to be in order. 

Note: I set "dynamic" to **T** in the [master spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539) so that this .Rmd file doesn't get overridden the next time `render_ste.R` is run. 
<img width="754" alt="Screen Shot 2022-02-14 at 2 24 27 PM" src="https://user-images.githubusercontent.com/59982410/153956697-d0f99a50-1ce8-450b-ab1b-29fe21d8a43d.png">

 

TODO:
- [ ] Figure out how a modal would appear to be populated even though its .Rmd script is empty/blank
- [ ] Figure out why `insert_figure_meta` isn't happy

**Comment by mspector13** [comment]
Updating this issue to flag the scripts (that I'm aware of) that need TLC

- [ ] Human connections | Science
- [ ] Human connections | Education and engagement
- [ ] Human connections | Harvest
- [ ] Human connections | Nonconsumptive Recreation

@superjai do you have time to take a look?

**Comment by mspector13** [comment]
More troubleshooting documentation: 

I deleted `human-connections_education-engagement.html/.Rmd` from my local machine, and re-ran `render_site.R` to see what would happen. The .Rmd was recreated, and re-knit as `render_site.R` ran, but the result was the same (a totally blank .Rmd file even though the [spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539) is fully populated)

Maybe there's a silly spelling error I'm missing? Something's up...

**Comment by bbest** [comment]
## Images must be shared with `shares@nms4gargle.iam.gserviceaccount.com`

Here's the first issue: Images are not being downloaded because the they have not been shared with the required user `shares@nms4gargle.iam.gserviceaccount.com`. The `add_gimage_paths()` in `render_site.R` generates this CSV of problematic files:

`data/gsheets/figures_needs-to-be-fixed-or-shared_shares@nms4gargle.iam.gserviceaccount.com.csv`

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/bbest/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/bbest/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



link | image_link
-- | --
human-connections_education-engagement.html | https://drive.google.com/file/d/1Py3T2bPRz2SeQMUuUD-CQ3rxv7dcfvcg/view?usp=sharing
human-connections_education-engagement.html | https://drive.google.com/file/d/1XEJCXzDknoh459EQBYWJgXizMqDTbdoD/view?usp=sharing
human-connections_education-engagement.html | https://drive.google.com/file/d/1bOlymSCO7Wk7YlxcraSPXEDCCVlRVVov/view?usp=sharing
human-connections_education-engagement.html | https://drive.google.com/file/d/1oxOm1WroCicJwyQn1VY1wnt2WRfujvxR/view?usp=sharing
human-connections_education-engagement.html | https://drive.google.com/file/d/1lg_tPEYlDjRyQUs-XeQ35J7lvVi7nkZ8/view?usp=sharing
human-connections_harvest.html | https://drive.google.com/file/d/13HGDy7sAYBlZXnh_8DgEGQ9tu5nhIYsT/view?usp=sharing
human-connections_harvest.html | https://drive.google.com/file/d/19W2suaCA__GhEZ0EE5szFx8iePs__8l1/view?usp=sharing
human-connections_harvest.html | https://drive.google.com/file/d/1FE0-JhtoNZSUMAS7us3ZMFqzFWGiH93d/view?usp=sharing
human-connections_harvest.html | https://drive.google.com/file/d/1kIBu9_5NV8p2CAz9P9FS8_xzhw03OP4n/view?usp=sharing
human-connections_harvest.html | https://drive.google.com/file/d/15kl5cKqWXIFutgZagixjqnu2c0oYQ_RC/view?usp=sharing
human-connections_harvest.html | https://drive.google.com/file/d/1Lp9SPGkRPqIir6xMu7CTEB8VPqezuCER/view?usp=sharing
human-connections_marine-debris.html | https://drive.google.com/file/d/1z8Di6WaLqJav4G0g8fMVIXzmbhLYaZFK/view?usp=sharing
human-connections_nonconsumptive-recreation.html | https://drive.google.com/file/d/1zafDi4FcNOZnOLFTXT4SbzmMC0YS9-VZ/view?usp=sharing
human-connections_nonconsumptive-recreation.html | https://drive.google.com/file/d/1QoCmF8tLFq3Qb1fbFwOOJJp8s_gp5T0r/view?usp=sharing
human-connections_nonconsumptive-recreation.html | https://drive.google.com/file/d/1ho3chF_E7Cbl45zDxIx5r8zCgHZcODeI/view?usp=sharing
human-connections_science.html | https://drive.google.com/file/d/10ixfKS-nqqFlPZLZLQiqpZbKhQacbVCq/view?usp=sharing
human-connections_science.html | https://drive.google.com/file/d/1lg_tPEYlDjRyQUs-XeQ35J7lvVi7nkZ8/view?usp=sharing
human-connections_science.html | https://drive.google.com/file/d/1kqJrdc_dJDq8lc-nPK8dcYARi_MgxGXp/view?usp=sharing
human-connections_science.html | https://drive.google.com/file/d/1Gbh_07T7sFNB_Z3AFQmqEaGnJYJxUFHs/view?usp=sharing
human-connections_vessels.html | https://drive.google.com/file/d/1tTZEF6RRb2BviW9B6ATDSqZ40uEFAAdt/view?usp=sharing
human-connections_vessels.html | https://drive.google.com/file/d/1jqF1-x2IhGXhBf7smEUbbe2SUsk-7kvY/view?usp=sharing
human-connections_wildlife-disturbance.html | https://drive.google.com/file/d/14ctB_iLiA_M_17LBb3RPWK9J8KQr7edE/view?usp=sharing
ocean-climate_nutrients-phytoplankton.html | https://drive.google.com/file/d/1OBB9tTPlEucGpagkcRstW0uGE8uEMIFR/view?usp=sharing
rocky-shore_barnacles.html | https://drive.google.com/file/d/1VbVDOru86cmDJrUCYaBNNd2joC38pLxN/view?usp=sharing
rocky-shore_mussels.html | https://drive.google.com/file/d/1XK9Gwvb2cU9oaZXBQUM-jL2VcDEGIT85/view?usp=sharing
rocky-shore_ochre-star.html | https://drive.google.com/file/d/1ivwZ1IYV9b1Hd0vJt1CLW8KIMzRHenX-/view?usp=sharing



</body>

</html>

**Comment by bbest** [comment]
So the whole problem was because no figures were locally available to show in the modal, per the filter `!is.na(image_path)`:

https://github.com/noaa-onms/ocnms/blob/0c785936b638ffab587915cd582035147c8c722b/infographiqR.R#L215-L219

```r
df
```

```
# A tibble: 0 × 14
# … with 14 variables: ...1 <chr>, link <chr>,
#   tab_group <chr>, tab <chr>, image_link <chr>,
#   caption <chr>, monitoring_title <chr>,
#   monitoring_link <chr>, data_title <chr>, data_link <chr>,
#   comments <chr>, Images Needed <lgl>,
#   interactive_possible <chr>, image_path <chr>
```

Then fixing permissions and rerunning `add_gimage_paths()` in `render_site.R` downloads the necessary figures:

```r
df
```

```
# A tibble: 5 × 14
  ...1                 link  tab_group tab   image_link caption
  <chr>                <chr> <chr>     <chr> <chr>      <chr>  
1 education-engagement huma… NA        Tren… https://d… Bay Wa…
2 education-engagement huma… NA        Tren… https://d… Total …
3 education-engagement huma… NA        Tren… https://d… Impres…
4 education-engagement huma… NA        Tren… https://d… Number…
5 education-engagement huma… NA        Tren… https://d… The nu…
# … with 8 more variables: monitoring_title <chr>,
#   monitoring_link <chr>, data_title <chr>, data_link <chr>,
#   comments <chr>, Images Needed <lgl>,
#   interactive_possible <chr>, image_path <chr>
```

Now we're adding a very explicit message to `create_modal()` like so for this problem in future:

```
WHOAH! For `link` == human-connections_education-engagement.html,
missing 2 figures locally (not downloaded by `add_gimage_paths()`) that were
defined in Google Sheet:
- https://drive.google.com/file/d/1oxOm1WroCicJwyQn1VY1wnt2WRfujvxR/view?usp=sharing
- https://drive.google.com/file/d/1lg_tPEYlDjRyQUs-XeQ35J7lvVi7nkZ8/view?usp=sharing
This usually means `add_gimage_paths()` had trouble with the `image_link` because:
  1) file wasn't shared with shares@nms4gargle.iam.gserviceaccount.com; or
  2) file is not an expected image, eg *png or *jpeg.
```
