### ISSUE TITLE
reduce big images, manually for now

### ISSUE THREAD

**Issue by bbest** [noaa-onms/ocnms#7]
Hey @mspector13,

Can you please reduce all images in `figures/` to being less than 1 MB in size, upload to Gdrive and update the Gsheet [Master_OCNMS_infographic_content](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539) with the smaller `image_link` accordingly?

![image](https://user-images.githubusercontent.com/2837257/130849104-630a29b8-f965-42db-8eb2-e54cef24e1cd.png)

You'll need to reference the `image_path` column in [`data/gsheets/figures.csv`](https://github.com/noaa-onms/ocnms/blob/master/data/gsheets/figures.csv) and when done run:

```r
source("render_site_v2.R")
```

**Comment by mspector13** [comment]
Ok, it turns out that only about 9 figures were > 1MB so I only reduced those ones. Instead of messing with the original folders, I added them to a new shared folder [Figures_reduced](https://drive.google.com/drive/folders/1P2ky9rCL3IDNF6nVrF-6x23ZgwMj5HxZ?usp=sharing) and made sure to share the folder + individual images with [the "shares" email account](shares@nms4gargle.iam.gserviceaccount.com)

However, when I try to run `source("render_site_v2.R")` I get the following error:

`Error: file.exists(google_sa_json) is not TRUE`

Also, Line 34 in the [master ocnms spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539) (fish-assemblage, Trends - black rockfish) currently calls figures/Appendix S.LR.13.19 - Density of red urchins in kelp forest 2015-2019.jpg which is weird... is that a mistake?

**Comment by bbest** [comment]
Please see [test_gs4_auth.Rmd](https://github.com/noaa-onms/ocnms/blob/master/test_gs4_auth.Rmd) for more on how you can point to the path for your authorization JSON file.

**Comment by mspector13** [comment]
Right on, thanks for your patience @bbest! I added the pathway to my JSON credentials in `render_site_v2.R" on line 21:

![Screen Shot 2021-09-08 at 12 40 51 PM](https://user-images.githubusercontent.com/59982410/132574789-483a2d10-70db-4028-b610-a105e7a72ba4.png)

It took a while for `create_modals()` and `render_modals()` to execute for the first time, but so far everything looks relatively good within individual modal windows. 

However, as noted in noaa-onms/ocnms/issues/#15 we need to finalize modal window templates

Further, as noted in issue #11 we need to get Scenes working as well. This is what happens when I try to knit any of the scenes (e.g. `kelp_forest.Rmd`)

![Screen Shot 2021-09-08 at 12 43 13 PM](https://user-images.githubusercontent.com/59982410/132575253-309a43e9-a008-4cc8-b827-56c5385f2006.png)

If I'm understanding this error message correctly, `r infographiqR::ocnms_get_modal_info()` is looking for a sheet named "pages" in the [ocnms master spreadsheet](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1920488482). Does that mean we just need to change the syntax in `r infographiqR::ocnms_get_modal_info()`?
